export const demoClinics = [
  {
    id: 1,
    type: "clinic",
    name: "City Clinic",
    logo: "🏥",
    specialization: "Umumiy shifokorlik",
    hours: "09:00 - 18:00",
    rating: 4.8,
    price: "150,000",
    distance: "2.3 km",
    address: "Tashkent, Amir Temur ko'chasi 12",
    phone: "+998 71 123 45 67",
  },
  {
    id: 2,
    type: "doctor",
    name: "Dr. Samad Karimov",
    avatar: "👨‍⚕️",
    specialization: "Kardiolog",
    experience: "15 yil",
    rating: 4.9,
    price: "200,000",
    distance: "1.5 km",
  },
  {
    id: 3,
    type: "gym",
    name: "FitLife Sport Zali",
    image: "🏋️",
    trainings: ["Fitnes", "Yoga", "Boks"],
    monthlyPrice: "350,000",
    rating: 4.7,
    distance: "3.1 km",
  },
  {
    id: 4,
    type: "medicine",
    name: "Paracetamol 500mg",
    image: "💊",
    price: "12,000",
    rating: 4.6,
    stock: true,
  },
  {
    id: 5,
    type: "clinic",
    name: "Heart Center",
    logo: "❤️",
    specialization: "Kardiologiya",
    hours: "08:00 - 17:00",
    rating: 4.9,
    price: "250,000",
    distance: "4.2 km",
    address: "Tashkent, Mustaqillik 45",
    phone: "+998 71 234 56 78",
  },
  {
    id: 6,
    type: "doctor",
    name: "Dr. Maryam Azimova",
    avatar: "👩‍⚕️",
    specialization: "Pediatr",
    experience: "10 yil",
    rating: 5.0,
    price: "180,000",
    distance: "2.8 km",
  },
  {
    id: 7,
    type: "clinic",
    name: "Wellness Clinic",
    logo: "🏥",
    specialization: "Dermatologiya",
    hours: "09:00 - 19:00",
    rating: 4.6,
    price: "180,000",
    distance: "3.5 km",
    address: "Tashkent, Mirzo Ulug‘bek 23",
    phone: "+998 71 345 67 89",
  },
  {
    id: 8,
    type: "doctor",
    name: "Dr. Rustam Tursunov",
    avatar: "👨‍⚕️",
    specialization: "Nevrolog",
    experience: "12 yil",
    rating: 4.7,
    price: "220,000",
    distance: "2.1 km",
  },
  {
    id: 9,
    type: "gym",
    name: "PowerHouse Gym",
    image: "🏋️",
    trainings: ["Crossfit", "Gymnastics", "Weightlifting"],
    monthlyPrice: "400,000",
    rating: 4.9,
    distance: "1.8 km",
  },
  {
    id: 10,
    type: "medicine",
    name: "Ibuprofen 200mg",
    image: "💊",
    price: "15,000",
    rating: 4.5,
    stock: true,
  },
  {
    id: 11,
    type: "clinic",
    name: "Smile Dental",
    logo: "🦷",
    specialization: "Stomatologiya",
    hours: "10:00 - 20:00",
    rating: 4.8,
    price: "120,000",
    distance: "2.0 km",
    address: "Tashkent, Chilonzor 8",
    phone: "+998 71 456 78 90",
  },
  {
    id: 12,
    type: "doctor",
    name: "Dr. Nilufar Qodirova",
    avatar: "👩‍⚕️",
    specialization: "Ginekolog",
    experience: "8 yil",
    rating: 4.9,
    price: "210,000",
    distance: "3.2 km",
  },
  {
    id: 13,
    type: "gym",
    name: "Yoga Bliss",
    image: "🧘",
    trainings: ["Yoga", "Meditatsiya", "Pilates"],
    monthlyPrice: "320,000",
    rating: 4.6,
    distance: "4.0 km",
  },
  {
    id: 14,
    type: "medicine",
    name: "Vitamin C 500mg",
    image: "💊",
    price: "25,000",
    rating: 4.8,
    stock: true,
  },
  {
    id: 15,
    type: "clinic",
    name: "NeuroCare",
    logo: "🧠",
    specialization: "Nevrologiya",
    hours: "09:00 - 18:00",
    rating: 4.7,
    price: "230,000",
    distance: "5.1 km",
    address: "Tashkent, Yunusobod 16",
    phone: "+998 71 567 89 01",
  },
  {
    id: 16,
    type: "doctor",
    name: "Dr. Javlonbek To‘xtayev",
    avatar: "👨‍⚕️",
    specialization: "Ortoped",
    experience: "14 yil",
    rating: 4.8,
    price: "190,000",
    distance: "3.0 km",
  },
  {
    id: 17,
    type: "gym",
    name: "CrossFit Arena",
    image: "🏋️",
    trainings: ["Crossfit", "HIIT", "Strength"],
    monthlyPrice: "420,000",
    rating: 4.9,
    distance: "2.5 km",
  },
  {
    id: 18,
    type: "medicine",
    name: "Amoxicillin 500mg",
    image: "💊",
    price: "30,000",
    rating: 4.6,
    stock: true,
  },
];
