export const demoClinics = [
  {
    id: 1,
    type: "clinic",
    name: "City Clinic",
    logo: "🏥",
    specialization: "Umumiy shifokorlik",
    hours: "09:00 - 18:00",
    rating: 4.8,
    price: "150,000",
    distance: "2.3 km",
    address: "Tashkent, Amir Temur ko'chasi 12",
    phone: "+998 71 123 45 67",
  },
  {
    id: 2,
    type: "doctor",
    name: "Dr. Samad Karimov",
    avatar: "👨‍⚕️",
    specialization: "Kardiolog",
    experience: "15 yil",
    rating: 4.9,
    price: "200,000",
    distance: "1.5 km",
  },
  {
    id: 3,
    type: "gym",
    name: "FitLife Sport Zali",
    image: "🏋️",
    trainings: ["Fitnes", "Yoga", "Boks"],
    monthlyPrice: "350,000",
    rating: 4.7,
    distance: "3.1 km",
  },
  {
    id: 4,
    type: "medicine",
    name: "Paracetamol 500mg",
    image: "💊",
    price: "12,000",
    rating: 4.6,
    stock: true,
  },
  {
    id: 5,
    type: "clinic",
    name: "Heart Center",
    logo: "❤️",
    specialization: "Kardiologiya",
    hours: "08:00 - 17:00",
    rating: 4.9,
    price: "250,000",
    distance: "4.2 km",
    address: "Tashkent, Mustaqillik 45",
    phone: "+998 71 234 56 78",
  },
  {
    id: 6,
    type: "doctor",
    name: "Dr. Maryam Azimova",
    avatar: "👩‍⚕️",
    specialization: "Pediatr",
    experience: "10 yil",
    rating: 5.0,
    price: "180,000",
    distance: "2.8 km",
  },
];
